data:extend({    
    {
        type = "bool-setting",
        name = "mushroom-cloud-play-sounds",
        setting_type = "runtime-global",
        default_value = true,
        order  = "a",
    },
    {
        type = "int-setting",
        name = "mushroom-cloud-radius-1",
        setting_type = "runtime-global",
        default_value = 150,
        minimum_value = 50,
        maximum_value = 2000,
        order = "b-a",
    },
    {
        type = "int-setting",
        name = "mushroom-cloud-radius-2",
        setting_type = "runtime-global",
        default_value = 400,
        minimum_value = 250,
        maximum_value = 5000,
        order = "b-b",
    },
    {
        type = "int-setting",
        name = "mushroom-cloud-radius-3",
        setting_type = "runtime-global",
        default_value = 7,
        minimum_value = 1,
        maximum_value = 25,
        order = "b-c",
    },        
    {
        type = "int-setting",
        name = "mushroom-cloud-radius-4",
        setting_type = "runtime-global",
        default_value = 25,
        minimum_value = 5,
        maximum_value = 100,
        order = "b-d",
    },        
})